/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisualClass;
import gnu.io.CommPortIdentifier;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import ObjClass.COMPortInfo;


public class COMPortSelectionWindow extends javax.swing.JFrame {

    /* Create COMPortInfo Object */
    COMPortInfo COMPort = new COMPortInfo();
    RequestMaterial RequestWindow = null; 
    
    public COMPortSelectionWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSearchCOM = new javax.swing.JButton();
        jButtonOpenCOM = new javax.swing.JButton();
        jComboBoxCOMPorts = new javax.swing.JComboBox<>();
        jLabelSelectTerminal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSearchCOM.setText("Search COM");
        jButtonSearchCOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCOMActionPerformed(evt);
            }
        });

        jButtonOpenCOM.setText("Open COM");
        jButtonOpenCOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenCOMActionPerformed(evt);
            }
        });

        jLabelSelectTerminal.setText("Select a terminal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSearchCOM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCOMPorts, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonOpenCOM, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSelectTerminal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabelSelectTerminal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCOMPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchCOM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOpenCOM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchCOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCOMActionPerformed
        
        /* Get the COM ports connected to the computer */
        Enumeration COMPortsEnum = CommPortIdentifier.getPortIdentifiers();
        CommPortIdentifier COMPortId;
        String [] COMPortList = {"","","","","",""};
        int COMPortCount = 0;
        
        if (COMPortsEnum.hasMoreElements())
        {
            /* Get the list of the COM ports */
            while(COMPortsEnum.hasMoreElements())
            {
                COMPortId = (CommPortIdentifier) COMPortsEnum.nextElement();
                COMPortList[COMPortCount++] = COMPortId.getName();
            }
            jComboBoxCOMPorts.setModel(new javax.swing.DefaultComboBoxModel<>(COMPortList));
        }
        else
        {
            /* Display an error message, COM ports were not found */
            jComboBoxCOMPorts.setModel(new javax.swing.DefaultComboBoxModel<>(COMPortList));
            JOptionPane.showMessageDialog(rootPane, "Serial interfaces not detected");
        }
    }//GEN-LAST:event_jButtonSearchCOMActionPerformed

    private void jButtonOpenCOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenCOMActionPerformed
        
        if(jComboBoxCOMPorts.getSelectedItem().toString().isEmpty())
        {   
            /* Invalid COM port, display error message */
            JOptionPane.showMessageDialog(rootPane, "Can not open the serial interface");
        }
        else
        {
            /* Open the selected COM port */
            if(RequestWindow == null)
            {
                try
                {
                    COMPort.SetCOMPortName(jComboBoxCOMPorts.getSelectedItem().toString());
                    RequestWindow = new RequestMaterial(COMPort);
                    RequestWindow.setVisible(true);
                    this.setVisible(false);
                }
                catch(Exception exception)
                {
                    JOptionPane.showMessageDialog(rootPane, "Unexpected error\n\r" + exception.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButtonOpenCOMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(COMPortSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(COMPortSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(COMPortSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(COMPortSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new COMPortSelectionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOpenCOM;
    private javax.swing.JButton jButtonSearchCOM;
    private javax.swing.JComboBox<String> jComboBoxCOMPorts;
    private javax.swing.JLabel jLabelSelectTerminal;
    // End of variables declaration//GEN-END:variables
}
